name: Build

on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:

# Each container job mounts the runner host's system CA bundle (read-only)
# so that the internal CA cert is trusted for git, apt, and Node.js actions.
#
# One-time host setup on the runner machine:
#   sudo cp root_ca.crt /usr/local/share/ca-certificates/
#   sudo update-ca-certificates

jobs:
  build-linux:
    name: Linux amd64
    runs-on: docker
    container:
      image: catthehacker/ubuntu:act-22.04
      options: -v /etc/ssl/certs:/etc/ssl/certs:ro
    env:
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
      GIT_SSL_CAINFO: /etc/ssl/our_certs/root_ca.crt
    steps:
      - name: Create root_ca cert from Secret
        run: |
          # Create a directory and write the secret
          mkdir -p /etc/ssl/our_certs/
          echo "${{ secrets.ROOT_CA }}" > ./etc/ssl/our_certs/root_ca.crt
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install build dependencies
        run: |
          apt-get update -qq
          apt-get install -y --no-install-recommends \
            gcc libgl1-mesa-dev xorg-dev libxkbcommon-dev

      - name: Build
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 \
            go build -v -o marknote-linux-amd64 .

      - uses: actions/upload-artifact@v4
        with:
          name: marknote-linux-amd64
          path: marknote-linux-amd64

  build-windows:
    name: Windows amd64
    runs-on: docker
    container:
      image: catthehacker/ubuntu:act-22.04
      options: -v /etc/ssl/certs:/etc/ssl/certs:ro
    env:
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install cross-compilation toolchain
        run: |
          apt-get update -qq
          apt-get install -y --no-install-recommends \
            gcc-mingw-w64-x86-64

      - name: Build
        run: |
          CGO_ENABLED=1 GOOS=windows GOARCH=amd64 \
            CC=x86_64-w64-mingw32-gcc \
            go build -v -o marknote-windows-amd64.exe .

      - uses: actions/upload-artifact@v4
        with:
          name: marknote-windows-amd64
          path: marknote-windows-amd64.exe

  build-macos:
    name: macOS arm64
    runs-on: docker
    container:
      image: ghcr.io/shepherdjerred/macos-cross-compiler:latest
      options: -v /etc/ssl/certs:/etc/ssl/certs:ro
    env:
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
      GIT_SSL_CAINFO: /etc/ssl/certs/ca-certificates.crt
    steps:
      # Use git directly — actions/checkout is a JS action and this image
      # does not ship Node.js. The mounted cert bundle makes git trust the CA.
      - name: Check out code
        env:
          TOKEN: ${{ github.token }}
          SERVER_URL: ${{ github.server_url }}
        run: |
          git config --global --add safe.directory '*'
          HOST="${SERVER_URL#*://}"
          git clone "https://oauth2:${TOKEN}@${HOST}/${{ github.repository }}.git" .
          git checkout "${{ github.sha }}"

      - name: Install Node.js (required by upload-artifact)
        run: |
          apt-get update -qq
          apt-get install -y --no-install-recommends nodejs

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build
        run: |
          CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 \
            CC=aarch64-apple-darwin22-clang \
            go build -v -o marknote-darwin-arm64 .

      - uses: actions/upload-artifact@v4
        with:
          name: marknote-darwin-arm64
          path: marknote-darwin-arm64

  release:
    name: Release
    runs-on: docker
    needs: [build-linux, build-windows, build-macos]
    if: startsWith(github.ref, 'refs/tags/v')
    container:
      image: catthehacker/ubuntu:act-22.04
      options: -v /etc/ssl/certs:/etc/ssl/certs:ro
    env:
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            marknote-linux-amd64
            marknote-windows-amd64.exe
            marknote-darwin-arm64
